---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: nickdtodd/ansible-user-image:1.0
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 3
  config_options:
    defaults:
      become_user: nick
  inventory:
    host_vars:
      ubuntu:
        ansible_user: nick
verifier:
  name: ansible
  options:
    gather_facts: true
    sudo: true
